version: '3.8'

services:
  postgres:
    container_name: tiko_postgres
    image: postgres:13.13
    env_file:
      - .env
    volumes:
      - ./script/*.sql:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  app:
    container_name: tiko_nodejs
    image: node:16.13.2
    working_dir: /app
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - 8010:8010
    depends_on:
      - postgres
