version: '3.8'

services:
  postgres:
    container_name: tiko_postgres
    image: postgres:13.13
    env_file:
      - .env
    volumes:
      - ./script/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - 5432:5432

  app:
    container_name: tiko_nodejs
    command: npm run dev
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8010:8010
    depends_on:
      - postgres
